name: Visual Regression Tests

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lost-pixel:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://
      AUTH_SECRET: test
    steps:
      - uses: actions/checkout@v4
        #with:
        #ref: ${{ github.event.pull_request.head.sha || github.sha }} # HEAD commit instead of merge commit

      - uses: ./.github/actions/ci-setup

      - run: VISUAL_TESTING=true pnpm storybook:build

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.16.0
        env:
          LOST_PIXEL_API_KEY: 8b76db6c-b9f0-46d1-982f-70900a02690a
